version: "3.3"

volumes:
  pg_data:
    driver: local
  mongodb_data_container: 

networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: majoo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=majoo3,majoo4
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - ./majoo_data:/var/lib/postgresql/data_majoo
    ports:
      - 5432:5432
    networks:
      - backend
